### ISSUE TITLE
enjoy_motors_HS-8 / RIO Fernbedienung

### ISSUE THREAD

**Issue by plin2** [fhem/SD_Keeloq#19]
Upload zum Thread https://forum.fhem.de/index.php/topic,107239.msg1011885.html#msg1011885

Als Anlage ein Set von durchgespielten Tasten:

- eine Fernbedienung
- Aktoren 1-8 durchgespielt
- pro Aktor jeweils 10x up und 10x down

[rio-extract.log](https://github.com/fhem/SD_Keeloq/files/4049606/rio-extract.log)

**Comment by HomeAutoUser** [comment]
Mit https://github.com/fhem/SD_Keeloq/commit/92d3dbf9580d3b70f20a77286b4bde28f60a8328 wurde das neue Modell enjoy_motors_HS eingebunden.

HS-8 mit 8 Kanälen und HS-1 mit einem Kanal.
