### ISSUE TITLE
Pearl Warning im FHEM Log

### ISSUE THREAD

**Issue by meier81** [fhem/SD_Keeloq#20]
Hi und guten Abend,

hab heute mal wieder mein Log durchgeschaut bezüglich Fehler usw., da ist mir folgende Zeile des öfteren ins Auge gefallen (natürlich immer mit anderem Datum und Uhrzeit):

`2020.06.05 20:45:09 1: PERL WARNING: Use of uninitialized value $binsplit in concatenation (.) or string at ./FHEM/14_SD_Keeloq.pm line 601.`

Da Pearl-Code nicht unbedingt mein Steckenpferd ist könnte sich das von euch mal jemand ansehen?

Gruß Markus

**Comment by HomeAutoUser** [comment]
Hallo @meier81,
kannst du bitte mal das Modul auf den aktuellen Stand bringen und verfolgen ob die Meldung immer noch auftritt?
Es könnte passieren, das wir dazu die passenden Empfangsnachrichten benötigen um den Fall nachzustellen.

LG

**Comment by bismosa** [comment]
Hallo!
Das "Problem" habe ich auch gelegentlich. 15x im letzten Monat.
Ich habe die 
`# $Id: 14_SD_Keeloq.pm 32 2019-09-02 09:56:00Z v3.4 $`
Das ist doch die aktuelle?
Gruß Bismosa

**Comment by HomeAutoUser** [comment]
Hallo,

>Das ist doch die aktuelle?

Ich habe erst heute gerade die letzte pre_release Version ins Master geschoben.
Es wäre schön wenn ihr beide auf diesem Stand wäret.

Wenn ich den Fehler richtig einschätze, so benötigen wir vermutlich die passende RAWMSG um es zu provozieren.
Solltet Ihr die RAWMSG´s mit ins Logfile schreiben lassen, so wäre ein Blick vielleicht hilfreich.

Beim Auftreten des Fehlers, ob da Zeitgleich im Logfile von einem Device eine RAWMSG steht.
Wenn ja, her damit.

Sollte das nicht der Fall sein, so kann es passieren, das man das Logfile vom SIGNALduino mal auf verbose 4 laufen lassen müsste um den Fall zu erfassen. Nur dann kann ich ggf dort den Fehler nachvollziehen.

LG Marco

**Comment by bismosa** [comment]
Hallo!
Gerade das Update gemacht. Nach einem Reload einmal einen Rolladen bewegt:
```
2020.12.03 18:01:26 1: PERL WARNING: Use of uninitialized value $binsplit in concatenation (.) or string at ./FHEM/14_SD_Keeloq.pm line 677.
2020.12.03 18:01:26 3: SIGNALduino: SD_Rollo_16ch set up 9
```
Ich habe nun mal auf Verbose 5 geloggt...konnte aber den Fehler leider nicht reproduzieren...
Ich lasse das mal ein bisschen laufen...

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
👋 ich schaue mal mit der Zeilennummern in den Code. Ich habe einen Verdacht.

Vielleicht kannst du die Meldung provozieren nach einem shutdown restart / Rolladen steuern. Warnings werden meist nur einmal angezeigt nachdem das System die Variablen das erste mal ansprach.

Grüße Marco

**Comment by bismosa** [comment]
Hallo!

Ich habe gerade noch diesen Eintrag neu:
`2020.12.03 20:14:09 1: PERL WARNING: Use of uninitialized value $binsplit in concatenation (.) or string at ./FHEM/14_SD_Keeloq.pm line 986.`
Leider kein weiteren Log dazu.
Ich vermute, das es eine andere Fernbedienung war, bei der ich noch nicht Verbose 5 eingestellt habe.

Durch ein "shutdown restart" und danach probieren kann ich es nicht provozieren...mehrfach getestet. Ich kann leider im Moment den Raspberry nicht neu starten, da andere Dinge darauf laufen, die nicht unterbrochen werden können.

Gruß
Bismosa

**Comment by bismosa** [comment]
Hallo!
Auch jetzt nach einigen Tagen auf Verbose 5..."leider" kein neuer Eintrag des Fehlers im Log. 
Auch nicht nach Neustart etc,
Vielleicht doch schon behoben?

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
@bismosa 
es kann sein, das der Fehler behoben ist oder dieser nur bei einer bestimmten Konstellation generiert wird.
Da hilft nur abwarten.

@meier81, hattest du mal ein Update vollzogen vom Modul und feststellen können ob der Fehler noch auftritt?

Gruß vom Weihnachtswichtel ;-)

**Comment by HomeAutoUser** [comment]
@meier81 @bismosa 
Erneute Anfrage was die Meldungen machen?

**Comment by bismosa** [comment]
Hallo!
Gerade mal meine Logs durchgesehen. Ich lasse es immer noch auf Verbose 5 laufen...aber bisher kein Fehler aufgetaucht.
Ich denke, dann sollte das behoben sein?
Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
@bismosa , @meier81 
bitte mal die Version
`update force https://raw.githubusercontent.com/fhem/SD_Keeloq/pre-release/controls_SD_Keeloq.txt`
testen weil ein Fix (https://github.com/fhem/SD_Keeloq/issues/21) drin war, welcher korrigiert wurde.

Ich würde gern ebenso euer GO erhalten das die Version funktioniert.

**Comment by bismosa** [comment]
Hallo!
https://raw.githubusercontent.com/fhem/SD_Keeloq/pre-release/controls_SD_Keeloq.txt - 404: Not Found ?
Fehler im Link? Oder schon entfernt?

Gruß
Bismosa

**Comment by bismosa** [comment]
Hallo!

Sorry, ich bin erst jetzt dazu gekommen die Version auszutauschen und zu testen.
Ich hab es ausgetauscht und wollte nun mein Verbose wieder zurück stellen. War mir nicht sicher, ob etwas bei Verbose 2 geloggt wird und probierte es direkt aus...hier hatte ich wieder einen Fehler:
```
2021.01.16 08:31:01 3: SD_Keeloq: set attr verbose to 2
2021.01.16 08:31:10 1: PERL WARNING: Use of uninitialized value $binsplit in concatenation (.) or string at ./FHEM/14_SD_Keeloq.pm line 679.
```
Natürlich kann ich jetzt keine weiteren Infos geben, da Verbose ja gerade umgestellt war. 

Noch vor der Umstellung des Verbose hatte ich keinen Fehler im Log. Mein Log ist durch das testen mittlerweile auf >13000 Zeilen...nichts.

Das war direkt nach dem Austauschen des Moduls:
```
2021.01.16 08:28:36 1: PERL WARNING: Subroutine SD_Keeloq_attr2htmlButtons redefined at ./FHEM/14_SD_Keeloq.pm line 1465.
2021.01.16 08:29:06 4: ######## DEBUG SET - START ########
2021.01.16 08:29:06 4: SIGNALduino: SD_Keeloq_Set - cmd=up cmd2=9 args cmd2=1 addGroups=Strassenseite:1,2,3 ALLE:1,2,3,4,5,6,7,8,9
2021.01.16 08:29:06 4: SIGNALduino: SD_Keeloq_Set - check, foreachCount=1 function=up cmd=up
2021.01.16 08:29:06 4: SIGNALduino: SD_Keeloq_Set - check, foreachLoop=1 LearnVersion=new (send updown and additionally followed stop)
2021.01.16 08:29:06 4: SIGNALduino: SD_Keeloq_Set - check, multiple selection: no
2021.01.16 08:29:06 4: SIGNALduino: SD_Keeloq_Set - channel via setlist       => button=up buttonbits=1000 channel=9
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - Channel                   = 9
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - Channelpart1 (Group 0-7)  = 00000000
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - Channelpart2 (Group 8-15) = 00000001
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - Button                    = up
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - Button_bits               = 1000
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - DeviceKey                 = 178913288
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - Device_key_lsb            = 2626740595
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - Device_key_msb            = 264549753
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - disc                      = 0000000000001000
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - result (decode)           = 535827
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - Counter                   = 11539
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - encoded (encrypt)         = 01010100000110100100111011111010

2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set                                           encoded     <- | ->     decrypts
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set                       Grp 0-7 |digitS/N|      counter    | ch |          serial        | bt |Grp 8-15
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - bits (send split) = 01011111 01110010 01011000 00101010 0001 000000000000010101010101 0001 10000000
2021.01.16 08:29:06 5: SIGNALduino: SD_Keeloq_Set - bits (send)       = 010111110111001001011000001010100001000000000000010101010101000110000000
2021.01.16 08:29:06 4: SIGNALduino: SD_Keeloq_Set - sendMSG           = P87#010111110111001001011000001010100001000000000000010101010101000110000000P#R5
2021.01.16 08:29:06 4: ######## DEBUG SET - END ########
2021.01.16 08:29:06 3: SIGNALduino: SD_Rollo_16ch set up 9
2021.01.16 08:29:09 4: ######## DEBUG SET - START ########
2021.01.16 08:29:09 4: SIGNALduino: SD_Keeloq_Set - cmd=up cmd2=9 args cmd2=1 addGroups=Strassenseite:1,2,3 ALLE:1,2,3,4,5,6,7,8,9
2021.01.16 08:29:09 4: SIGNALduino: SD_Keeloq_Set - check, foreachCount=1 function=up cmd=up
2021.01.16 08:29:09 4: SIGNALduino: SD_Keeloq_Set - check, foreachLoop=1 LearnVersion=new (send updown and additionally followed stop)
2021.01.16 08:29:09 4: SIGNALduino: SD_Keeloq_Set - check, multiple selection: no
2021.01.16 08:29:09 4: SIGNALduino: SD_Keeloq_Set - channel via setlist       => button=up buttonbits=1000 channel=9
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - Channel                   = 9
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - Channelpart1 (Group 0-7)  = 00000000
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - Channelpart2 (Group 8-15) = 00000001
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - Button                    = up
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - Button_bits               = 1000
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - DeviceKey                 = 178913288
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - Device_key_lsb            = 2626740595
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - Device_key_msb            = 264549753
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - disc                      = 0000000000001000
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - result (decode)           = 535828
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - Counter                   = 11540
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - encoded (encrypt)         = 01101101011101101100111110101010

2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set                                           encoded     <- | ->     decrypts
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set                       Grp 0-7 |digitS/N|      counter    | ch |          serial        | bt |Grp 8-15
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - bits (send split) = 01010101 11110011 01101110 10110110 0001 000000000000010101010101 0001 10000000
2021.01.16 08:29:09 5: SIGNALduino: SD_Keeloq_Set - bits (send)       = 010101011111001101101110101101100001000000000000010101010101000110000000
2021.01.16 08:29:09 4: SIGNALduino: SD_Keeloq_Set - sendMSG           = P87#010101011111001101101110101101100001000000000000010101010101000110000000P#R5
2021.01.16 08:29:09 4: ######## DEBUG SET - END ########
2021.01.16 08:29:09 3: SIGNALduino: SD_Rollo_16ch set up 9
2021.01.16 08:29:10 4: ######## DEBUG SET - START ########
2021.01.16 08:29:10 4: SIGNALduino: SD_Keeloq_Set - cmd=stop cmd2=9 args cmd2=1 addGroups=Strassenseite:1,2,3 ALLE:1,2,3,4,5,6,7,8,9
2021.01.16 08:29:10 4: SIGNALduino: SD_Keeloq_Set - check, foreachCount=1 function=stop cmd=stop
2021.01.16 08:29:10 4: SIGNALduino: SD_Keeloq_Set - check, foreachLoop=1 LearnVersion=new (send updown and additionally followed stop)
2021.01.16 08:29:10 4: SIGNALduino: SD_Keeloq_Set - check, multiple selection: no
2021.01.16 08:29:10 4: SIGNALduino: SD_Keeloq_Set - channel via setlist       => button=stop buttonbits=0100 channel=9
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - Channel                   = 9
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - Channelpart1 (Group 0-7)  = 00000000
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - Channelpart2 (Group 8-15) = 00000001
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - Button                    = stop
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - Button_bits               = 0100
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - DeviceKey                 = 178913288
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - Device_key_lsb            = 2626740595
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - Device_key_msb            = 264549753
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - disc                      = 0000000000001000
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - result (decode)           = 535829
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - Counter                   = 11541
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - encoded (encrypt)         = 11011111001000111000010101011111

2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set                                           encoded     <- | ->     decrypts
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set                       Grp 0-7 |digitS/N|      counter    | ch |          serial        | bt |Grp 8-15
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - bits (send split) = 11111010 10100001 11000100 11111011 0001 000000000000010101010101 0010 10000000
2021.01.16 08:29:10 5: SIGNALduino: SD_Keeloq_Set - bits (send)       = 111110101010000111000100111110110001000000000000010101010101001010000000
2021.01.16 08:29:10 4: SIGNALduino: SD_Keeloq_Set - sendMSG           = P87#111110101010000111000100111110110001000000000000010101010101001010000000P#R5
2021.01.16 08:29:10 4: ######## DEBUG SET - END ########
2021.01.16 08:29:10 3: SIGNALduino: SD_Rollo_16ch set stop 9
```
Also kein Fehler.


Ich verstehe es auch nicht so ganz. Zeile 679 ist:
`Log3 $name, 5, "$ioname: SD_Keeloq_Set - bits (send split) = $binsplit";`
$binsplit sollte ja auch leer sein, es wird ja nur gesetzt in Zeile 675, wenn verbose auf 5 
`my $binsplit = SD_Keeloq_binsplit_JaroLift($bits) if (AttrVal($name, "verbose", "3") eq "5");`

Somit sollte es immer zu diesem Fehler kommen?

Gruß
Bismosa

**Comment by bismosa** [comment]
Nachtrag: Dieser Fehler ist auch im Log aufgetaucht:
```
2021.01.16 09:32:44 1: PERL WARNING: Use of uninitialized value $binsplit in concatenation (.) or string at ./FHEM/14_SD_Keeloq.pm line 988.
2021.01.16 09:32:45 1: PERL WARNING: Use of uninitialized value $binsplit in concatenation (.) or string at ./FHEM/14_SD_Keeloq.pm line 988, <GEN95> line 12.
2021.01.16 09:33:46 1: PERL WARNING: Use of uninitialized value $binsplit in concatenation (.) or string at ./FHEM/14_SD_Keeloq.pm line 679.
```
Ich schaue mir das später nochmal an.

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
@bismosa du kannst gern die neue Version testen.
Ich habe die Stellen überarbeitet.

**Comment by bismosa** [comment]
Hallo!

Scheint alles zu laufen :) 
Bisher sind keine weiteren Fehler aufgefallen.
DANKE!

Gruß
Bismosa
